In [8]:
import numpy as np
import matplotlib.pyplot as plt

In [9]:
def power_iteration(A, x0, max_iterations, tol = np.finfo(float).eps):
    """
    Perform power iteration to find the dominant eigenvector and eigenvalue of a square matrix.

    Parameters:
    - A (numpy.ndarray): The square matrix for which to find the dominant eigenvector and eigenvalue.
    - x0 (numpy.ndarray): The initial guess for the eigenvector.
    - max_iterations (int): The maximum number of iterations to perform.
    - tol (float): Convergence tolerance. The iteration stops if the change in eigenvalue is below this threshold.

    Returns:
    - x (numpy.ndarray): The dominant eigenvector.
    - lamda (float): The corresponding dominant eigenvalue.
    """
    x = x0.copy()
    x = x/np.linalg.norm(x)
    lamda=0
    for _ in range(max_iterations):
        x = A@x
        x = x/np.linalg.norm(x)
        lamda_new = np.dot(x, A@x)
        if np.abs(lamda_new - lamda) < tol:
            break
        lamda = lamda_new

    return x, lamda

In [10]:
A = np.array([[2,0],[0,-2]])
x0 = np.array([1,0])
x1 = np.array([0,1])
x2 = np.array([1,1])

In [5]:
# It converges to the first eigenvalue
power_iteration(A,x0,50)

(array([1., 0.]), 2.0)

In [6]:
# It converges to the second eigenvalue
power_iteration(A,x1,50)

(array([0., 1.]), -2.0)

In [7]:
# It does not converge
power_iteration(A,x2,50)

(array([ 0.70710678, -0.70710678]), 0)

The problem is that $||\lambda_1||_2 = ||\lambda_2||_2$. Remark 7.3.
Basically, in this case the algorithm converges to the normalised initial vector and the corresponding eigenvalue.
Case x0 and x1 above are mere artifacts and lucky cases.


In [57]:
A = np.array([[2,0],[0,1]])
x0 = np.array([1,0])
x1 = np.array([0.1,0.9999])

In [31]:
power_iteration(A,x1,50)

(array([1.00000000e+00, 9.31229442e-09]), 2.0)

In [45]:
Q, R = np.linalg.qr(A)

In [46]:
Q

array([[-0.9701425 ,  0.10585122],
       [-0.        , -0.89973541],
       [-0.24253563, -0.4234049 ]])

In [47]:
R

array([[-2.06155281, -0.12126781],
       [ 0.        , -1.11143786]])

In [40]:
Q, R = np.linalg.qr(A, mode='complete')

In [41]:

Q

array([[-0.9701425 ,  0.10585122, -0.21821789],
       [-0.        , -0.89973541, -0.43643578],
       [-0.24253563, -0.4234049 ,  0.87287156]])

In [42]:
np.matmul(Q, Q.T)

array([[ 1.00000000e+00, -9.75133365e-19,  2.97058423e-17],
       [-9.75133365e-19,  1.00000000e+00,  3.90053346e-18],
       [ 2.97058423e-17,  3.90053346e-18,  1.00000000e+00]])

In [43]:
np.matmul(Q.T, Q)

array([[ 1.00000000e+00, -1.90447000e-17,  3.66062534e-17],
       [-1.90447000e-17,  1.00000000e+00, -6.73594335e-20],
       [ 3.66062534e-17, -6.73594335e-20,  1.00000000e+00]])

In [44]:
R

array([[-2.06155281, -0.12126781],
       [ 0.        , -1.11143786],
       [ 0.        ,  0.        ]])

In [65]:
def QR (A, M, iterations):
    X = M.copy()
    for _ in range(iterations):
        Q,R = np.linalg.qr(X)
        print(Q)
        X = A@Q
        print(X)
    return X


In [60]:
A = np.array([[1,5],[3,6]])

In [62]:
np.linalg.eigvals(A)

array([-1.10977223,  8.10977223])

In [68]:
np.linalg.eig(A)

EigResult(eigenvalues=array([-1.10977223,  8.10977223]), eigenvectors=array([[-0.92133794, -0.57524923],
       [ 0.38876264, -0.81797819]]))

In [81]:
eigen = QR(A, np.array([[1,0],[0,1]]), 10)

[[ 1.  0.]
 [-0.  1.]]
[[1. 5.]
 [3. 6.]]
[[-0.31622777 -0.9486833 ]
 [-0.9486833   0.31622777]]
[[-5.05964426  0.63245553]
 [-6.64078309 -0.9486833 ]]
[[-0.60604322 -0.79543172]
 [-0.79543172  0.60604322]]
[[-4.58320182  2.23478436]
 [-6.59071997  1.24996413]]
[[-0.57092623 -0.82100136]
 [-0.82100136  0.57092623]]
[[-4.67593304  2.03362981]
 [-6.63878687  0.96255332]]
[[-0.5758388  -0.81756326]
 [-0.81756326  0.5758388 ]]
[[-4.66365508  2.06163073]
 [-6.63289594  1.00234301]]
[[-0.57516851 -0.81803495]
 [-0.81803495  0.57516851]]
[[-4.66534328  2.05780759]
 [-6.63371525  0.9969062 ]]
[[-0.57526027 -0.81797043]
 [-0.81797043  0.57526027]]
[[-4.66511241  2.05833093]
 [-6.63360338  0.99765035]]
[[-0.57524772 -0.81797926]
 [-0.81797926  0.57524772]]
[[-4.665144    2.05825932]
 [-6.63361869  0.99754852]]
[[-0.57524943 -0.81797805]
 [-0.81797805  0.57524943]]
[[-4.66513968  2.05826912]
 [-6.6336166   0.99756245]]
[[-0.5752492  -0.81797821]
 [-0.81797821  0.5752492 ]]
[[-4.66514027  2.058267

In [83]:
A@eigen[:,1]

array([ 7.0460705 , 12.16016659])

In [76]:
A

array([[1, 5],
       [3, 6]])

In [79]:
np.array(A)@np.array([[1,2],[3,4]])

array([[16, 22],
       [21, 30]])

In [73]:
power_iteration(A, np.array([1,2]), 10)

(array([0.57524923, 0.8179782 ]), 8.109772229317146)