In [2]:
import numpy as np
import matplotlib.pyplot as plt

In [3]:
def power_iteration(A, x0, max_iterations, tol = np.finfo(float).eps):
    """
    Perform power iteration to find the dominant eigenvector and eigenvalue of a square matrix.

    Parameters:
    - A (numpy.ndarray): The square matrix for which to find the dominant eigenvector and eigenvalue.
    - x0 (numpy.ndarray): The initial guess for the eigenvector.
    - max_iterations (int): The maximum number of iterations to perform.
    - tol (float): Convergence tolerance. The iteration stops if the change in eigenvalue is below this threshold.

    Returns:
    - x (numpy.ndarray): The dominant eigenvector.
    - lamda (float): The corresponding dominant eigenvalue.
    """
    x = x0.copy()
    x = x/np.linalg.norm(x)
    lamda=0
    for _ in range(max_iterations):
        x = A@x
        x = x/np.linalg.norm(x)
        lamda_new = np.dot(x, A@x)
        if np.abs(lamda_new - lamda) < tol:
            break
        lamda = lamda_new

    return x, lamda

In [4]:
A = np.array([[2,0],[0,-2]])
x0 = np.array([1,0])
x1 = np.array([0,1])
x2 = np.array([1,1])

In [5]:
# It converges to the first eigenvalue
power_iteration(A,x0,50)

(array([1., 0.]), 2.0)

In [6]:
# It converges to the second eigenvalue
power_iteration(A,x1,50)

(array([0., 1.]), -2.0)

In [7]:
# It does not converge
power_iteration(A,x2,50)

(array([ 0.70710678, -0.70710678]), 0)

The problem is that $||\lambda_1||_2 = ||\lambda_2||_2$. Remark 7.3.
Basically, in this case the algorithm converges to the normalised initial vector and the corresponding eigenvalue.
Case x0 and x1 above are mere artifacts and lucky cases.
