In [27]:
import numpy as np
import matplotlib.pyplot as plt

$A_l - \mu = Q_{l+1}R_{l+1} \Rightarrow Q_{l+1}^H \left(A_l - \mu \right) Q_{l+1} = R_{l+1}Q_{l+1} = A_{l+1}-\mu$

In [96]:
def QR(M, max_iter):
    """
    Apply the QR algorithm for finding eigenvalues of a matrix.

    Parameters:
    -----------
    M : array_like
        Input matrix for which eigenvalues are to be computed.
    max_iter : int
        Maximum number of iterations for the QR algorithm.

    Returns:
    --------
    A : ndarray
        Matrix representing the result after applying the QR algorithm.

    Notes:
    ------
    The QR algorithm iteratively decomposes the matrix `A` into `Q` and `R` at each
    iteration and updates `A` as `R @ Q`. The process is repeated for the specified
    number of iterations.

    Example:
    --------
    >>> M = np.array([[4, 2, 1],
    ...               [2, 3, 1],
    ...               [1, 1, 2]], dtype=float)
    >>> result = QR(M, max_iter=50)
    """
    
    A = M.copy()    
    for _ in range(max_iter):
        Q, R = np.linalg.qr(A)
        A = R @ Q
    return A


def QRwShift(M, max_iter, shift):
    """
    Apply the QR algorithm with a shift for finding eigenvalues of a matrix.

    Parameters:
    -----------
    M : array_like
        Input matrix for which eigenvalues are to be computed.
    max_iter : int
        Maximum number of iterations for the QR algorithm.
    shift : float or array_like
        Shift value or array to be subtracted from the original matrix during each iteration.

    Returns:
    --------
    A : ndarray
        Matrix representing the result after applying the QR algorithm with a shift.

    Notes:
    ------
    The QR algorithm with a shift iteratively decomposes the matrix `A - shift` into `Q` and `R` 
    at each iteration and updates `A` as `R @ Q + shift`. The process is repeated for the specified
    number of iterations.

    Example:
    --------
    >>> M = np.array([[4, 2, 1],
    ...               [2, 3, 1],
    ...               [1, 1, 2]], dtype=float)
    >>> result = QRwShift(M, max_iter=50, shift=2.0)
    """

    A = M.copy()

    for _ in range(max_iter):
        Q, R = np.linalg.qr(A - shift)
        A = R @ Q + shift
    return A



In [97]:
A = np.array([[3,-1,0,1],
              [-1,3,1,1],
              [0,1,3,0],
              [1,1,0,3]])

In [98]:
TRUE_EIGENVALS = np.linalg.eigvals(A)
TRUE_EIGENVALS

array([0.82991351, 2.68889218, 4.        , 4.4811943 ])

In [99]:
res = QRwShift(A,5, np.diag(np.diag(A))).diagonal()
print(res)
res = np.sort(res)


[0.85893417 4.44804857 4.00408381 2.68893345]


In [100]:
max(res-TRUE_EIGENVALS)

0.029020655905031667

In [101]:
np.linalg.norm(res-TRUE_EIGENVALS)

0.04424384011361339

In [102]:
B = A-np.diag(np.diag(A))
np.linalg.eigvals(B)+np.diag(A)

array([0.82991351, 2.68889218, 4.        , 4.4811943 ])