In [3]:
import numpy as np
import matplotlib.pyplot as plt

$A_l - \mu = Q_{l+1}R_{l+1} \Rightarrow Q_{l+1}^H \left(A_l - \mu \right) Q_{l+1} = R_{l+1}Q_{l+1} = A_{l+1}-\mu$

In [16]:
def QR(M, max_iter):
    """
    Apply the QR algorithm for finding eigenvalues of a matrix.

    Parameters:
    -----------
    M : array_like
        Input matrix for which eigenvalues are to be computed.
    max_iter : int
        Maximum number of iterations for the QR algorithm.

    Returns:
    --------
    A : ndarray
        Matrix representing the result after applying the QR algorithm.

    Notes:
    ------
    The QR algorithm iteratively decomposes the matrix `A` into `Q` and `R` at each
    iteration and updates `A` as `R @ Q`. The process is repeated for the specified
    number of iterations.

    Example:
    --------
    >>> M = np.array([[4, 2, 1],
    ...               [2, 3, 1],
    ...               [1, 1, 2]], dtype=float)
    >>> result = QR(M, max_iter=50)
    """
    
    A = M.copy()    
    for _ in range(max_iter):
        Q, R = np.linalg.qr(A)
        A = R @ Q
    return A


def QRwShift(M, max_iter, shift):
    """
    Apply the QR algorithm with a shift for finding eigenvalues of a matrix.

    Parameters:
    -----------
    M : array_like
        Input matrix for which eigenvalues are to be computed.
    max_iter : int
        Maximum number of iterations for the QR algorithm.
    shift : float or array_like
        Shift value or array to be subtracted from the original matrix during each iteration.

    Returns:
    --------
    A : ndarray
        Matrix representing the result after applying the QR algorithm with a shift.

    Notes:
    ------
    The QR algorithm with a shift iteratively decomposes the matrix `A - shift` into `Q` and `R` 
    at each iteration and updates `A` as `R @ Q + shift`. The process is repeated for the specified
    number of iterations.

    Example:
    --------
    >>> M = np.array([[4, 2, 1],
    ...               [2, 3, 1],
    ...               [1, 1, 2]], dtype=float)
    >>> result = QRwShift(M, max_iter=50, shift=2.0)
    """

    A = M.copy()

    for _ in range(max_iter):
        Q, R = np.linalg.qr(A - shift)
        A = R @ Q + shift
    return A





In [4]:
A = np.array([[3,-1,0,1],
              [-1,3,1,1],
              [0,1,3,0],
              [1,1,0,3]])

In [98]:
TRUE_EIGENVALS = np.linalg.eigvals(A)
TRUE_EIGENVALS

array([0.82991351, 2.68889218, 4.        , 4.4811943 ])

In [99]:
res = QRwShift(A,5, np.diag(np.diag(A))).diagonal()
print(res)
res = np.sort(res)


[0.85893417 4.44804857 4.00408381 2.68893345]


In [100]:
max(res-TRUE_EIGENVALS)

0.029020655905031667

In [101]:
np.linalg.norm(res-TRUE_EIGENVALS)

0.04424384011361339

In [102]:
B = A-np.diag(np.diag(A))
np.linalg.eigvals(B)+np.diag(A)

array([0.82991351, 2.68889218, 4.        , 4.4811943 ])

In [1]:
#Reyleigh shift is if you take the A[n,n]!!

In [19]:
def QRwShifting(M,max_iter, shift):


    A = M.copy()
    # Q,R = np.linalg.qr(A)
    for _ in range(max_iter):
        print(shift)
        Q, R = np.linalg.qr(A - shift)
        A = R @ Q + shift
        shift = R.T@(A@R)
        shift = shift/(np.dot(R.T, R))
    return A

In [20]:
QRwShifting(A, 15, shift = np.diag(np.diag(A))).diagonal()

[[3 0 0 0]
 [0 3 0 0]
 [0 0 3 0]
 [0 0 0 3]]
[[ 2.00000000e+00 -1.00000000e+00  2.00000000e+00  2.02996189e-16]
 [-1.00000000e+00  2.33333333e+00  4.54340209e+16 -1.00000000e+00]
 [ 2.00000000e+00  4.54340209e+16  3.00000000e+00  2.00000000e+00]
 [ 6.24714256e-16 -1.00000000e+00  2.00000000e+00  2.00000000e+00]]
[[ 3.77097670e+16  8.00419717e+16  2.57895978e+16  4.84000910e+16]
 [ 8.00419717e+16  5.54373703e+00  1.55903122e+33  1.84617525e+15]
 [ 2.57895978e+16  1.55903122e+33 -9.00639964e+15  1.24377073e+17]
 [ 4.84000910e+16  1.84617525e+15  1.24377073e+17  1.02569792e+16]]
[[-7.01553425e+32 -5.31099082e+33 -4.57650641e+32 -4.51323727e+33]
 [-5.31099082e+33  2.94947855e+17  5.51426823e+49  7.99478420e+31]
 [-4.57650641e+32  5.51426823e+49  3.07409550e+32 -1.49136084e+35]
 [-4.51323727e+33  7.99478420e+31 -1.49136084e+35  1.35736158e+32]]
[[-7.54654891e+48 -3.59098501e+50 -8.46763606e+48 -3.62710208e+50]
 [-3.59098501e+50  6.54657486e+33  1.45755912e+66  1.78582553e+46]
 [-8.46763606e

/var/folders/89/w_60r_4x0cj3g1zv6zj2235h0000gn/T/ipykernel_31060/2200948249.py:8: RuntimeWarning: overflow encountered in matmul
  shift = R.T@(A@R)


array([nan, nan, nan, nan])

In [13]:
np.linalg.norm(A, axis = 1)

array([3.31662479, 3.46410162, 3.16227766, 3.31662479])