In [4]:
import numpy as np
import numpy.linalg as la
import matplotlib.pyplot as plt


In [2]:
np.polynomial.legendre.leggauss(10)

(array([-0.97390653, -0.86506337, -0.67940957, -0.43339539, -0.14887434,
         0.14887434,  0.43339539,  0.67940957,  0.86506337,  0.97390653]),
 array([0.06667134, 0.14945135, 0.21908636, 0.26926672, 0.29552422,
        0.29552422, 0.26926672, 0.21908636, 0.14945135, 0.06667134]))

In [5]:
np.polynomial.legendre.Legendre((1,2))

3.0

In [18]:
A = np.array([[1,0,1],[1,1,0],[1,1,1]])
b = np.array([1,2,3])

In [19]:
la.det(A)

1.0

In [20]:
la.eig(A)

EigResult(eigenvalues=array([2.32471796+0.j        , 0.33764102+0.56227951j,
       0.33764102-0.56227951j]), eigenvectors=array([[-0.54843176+0.j        ,  0.43441848-0.3687798j ,
         0.43441848+0.3687798j ],
       [-0.41399889+0.j        , -0.65586562+0.j        ,
        -0.65586562-0.j        ],
       [-0.7265174 +0.j        , -0.08038366+0.48852922j,
        -0.08038366-0.48852922j]]))

In [7]:
la.eigvals(A)

array([0.5+0.8660254j, 0.5-0.8660254j, 2. +0.j       ])

In [8]:
la.solve(A, b)

array([0., 2., 1.])

In [22]:
A = np.array([[1,-2j],[2j,5]])

la.cholesky(A)

array([[1.+0.j, 0.+0.j],
       [0.+2.j, 1.+0.j]])

In [3]:
def harmonic(*args):
    summa = 0
    for i in args:
        summa+=1/i
    return summa

In [5]:
1/harmonic(1.17, 7.9, 14.0
         )

0.949927692093112

In [6]:
1/harmonic(1.47, 4.65, 6.4)

0.9509537317812776

In [7]:
1/harmonic(2.22, 3.5, 3.2)

0.953593618163688

In [8]:
1/harmonic(2.12, 3.45, 3.45)

0.9511053315994799

In [12]:
harmonic(4.05, 3.90, 1.73)

1.081358518738095